"""
Rules for adding transitions to embedded targets.

Heavily inspired / derived from: https://github.com/bazel-contrib/bazel-lib/blob/92420081885a1ea6bc54587b6e74ad2663f0678b/lib/transitions.bzl
"""

load("@bazel_skylib//lib:paths.bzl", "paths")


def _transition_impl(settings, attr):
    defines = []
    for define in attr.extra_defines:
        defines += ["-D" + str(define)]

    return {
        "//command_line_option:platforms": str(attr.target_platform),
        "//command_line_option:copt": settings["//command_line_option:copt"] + defines,
    }

_transition = transition(
    implementation = _transition_impl,
    inputs = [
        "//command_line_option:copt",
    ],
    outputs = [
        "//command_line_option:platforms",
        "//command_line_option:copt",
    ],
)

def _transition_binary_impl(ctx):
    # We need to forward the DefaultInfo provider from the underlying rule.
    # Unfortunately, we can't do this directly, because Bazel requires that the executable to run
    # is actually generated by this rule, so we need to symlink to it, and generate a synthetic
    # forwarding DefaultInfo.

    result = []

    # ctx.attr.binary is a singleton list if this rule uses an outgoing transition.
    if type(ctx.attr.binary) == type([]):
        binary = ctx.attr.binary[0]
    else:
        binary = ctx.attr.binary

    default_info = binary[DefaultInfo]
    files = default_info.files
    new_executable = None
    original_executable = default_info.files_to_run.executable
    runfiles = default_info.default_runfiles

    if not original_executable:
        fail("Cannot transition a 'binary' that is not executable")

    new_executable_name = ctx.attr.basename if ctx.attr.basename else original_executable.basename

    # In order for the symlink to have the same basename as the original
    # executable (important in the case of proto plugins), put it in a
    # subdirectory named after the label to prevent collisions.
    new_executable = ctx.actions.declare_file(paths.join(ctx.label.name, new_executable_name))
    ctx.actions.symlink(
        output = new_executable,
        target_file = original_executable,
        is_executable = True,
    )
    files = depset(direct = [new_executable], transitive = [files])
    runfiles = runfiles.merge(ctx.runfiles([new_executable]))

    result.append(
        DefaultInfo(
            files = files,
            runfiles = runfiles,
            executable = new_executable,
        ),
    )

    if RunEnvironmentInfo in binary:
        result.append(binary[RunEnvironmentInfo])

    return result

midsun_transition_binary = rule(
    implementation = _transition_binary_impl,
    attrs = {
        "basename": attr.string(),
        "target_platform": attr.label(mandatory = True),
        "extra_defines": attr.string_list(),
        "binary": attr.label(allow_files = True, cfg = _transition),
        "_allowlist_function_transition": attr.label(
            default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
        ),
    },
    executable = True,
)
