load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "system",
    srcs = ["hal_system.c", "syscalls.c"],
    target_compatible_with = [
        "@platforms//os:none",
        "@platforms//cpu:armv7e-mf",
    ],
    deps = ["@cmsis-device-g4//:system"],
    alwayslink = True,
)
