load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//bazel:transitions.bzl", "midsun_transition_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "blinky_cc",
    srcs = [
        "main.cpp",
    ],
    tags = ["manual"],
    deps = ["@stm32g4xx-hal-driver//:stm32g4xx_hal"],
)

midsun_transition_binary(
    name = "blinky",
    binary = "//blinky:blinky_cc",
    target_platform = "//bazel/platforms:stm32g4xx",
    extra_defines = [
        "STM32G474xx",
    ],
)
