load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//bazel:transitions.bzl", "midsun_transition_binary")

package(default_visibility = ["//visibility:public"])

exports_files(["linker.ld"])

cc_binary(
    name = "blinky_cc",
    srcs = [
        "main.cpp",
        "syscalls.c",
    ],
    additional_linker_inputs = ["//blinky:linker.ld"],
    linkopts = [
        "-Wl,-T $(location {})".format("//blinky:linker.ld"),
    ],
    tags = ["manual"],
    deps = [
        "//drivers/stm32g4xx:system",
        "@cmsis-device-g4//:startup_stm32g474xx",
        "@stm32g4xx-hal-driver//:stm32g4xx_hal",
    ],
)

midsun_transition_binary(
    name = "blinky",
    binary = "//blinky:blinky_cc",
    extra_defines = [
        "STM32G474xx",
    ],
    target_platform = "//bazel/platforms:stm32g4xx",
)
